import type { Metadata } from 'next'
import { rubik } from './ui/fonts'

import './globals.css'
import Header from './components/Header'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <div className='w-[80%] m-auto mt-[50px]'>
          <Header/>
          {children}
        </div>
       
      </body>
    </html>
  )
}
