import type { Metadata } from 'next'
import { rubik } from './ui/fonts'
import './globals.css'
import { QuestionProvider } from './context/questionContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <QuestionProvider>
          {children}
        </QuestionProvider>
      </body>
    </html>
  )
}
